### ISSUE TITLE
问题：日期全部为2022/7/31；建议：按照地区安置校园

### ISSUE THREAD

**Issue by Lhcfl** [mtf-wiki/RLE-wiki#27]
如题。目前wiki中所有条目的日期被统一变成了2022/7/31。同时，导航栏中对学校没有合适的组织方式（似乎既不是按拼音也不是按地区）

**Comment by septs** [comment]
1. 最后修改时间是基于 git 的
2. 建立二级分类将提高检索成本（e.g: MtF.wiki 的精神科）
3. 排序策略问题建议另开 issue 进行讨论

**Comment by Lhcfl** [comment]
> 最后修改时间是基于 git 的

不可以像hexo一样在文档里修改时间吗？

**Comment by Lhcfl** [comment]
@septs 
经本地确认，在文件头添加时间，即可修改最后修改时间。

例如
```
---
title: 湖南大学
author: 喵死你，或者挠死你
date: 2019-11-17 15:56:01
---
```

则该文档的时间会被修改为2019-11-17

**Comment by Lhcfl** [comment]
![](https://pic.imgdb.cn/item/62ea85f116f2c2beb188eeab.jpg)

本地构建的结果

**Comment by septs** [comment]
> 1. 最后修改时间是基于 git 的
> 2. 建立二级分类将提高检索成本（e.g: MtF.wiki 的精神科）
> 3. 排序策略问题建议另开 issue 进行讨论

问题 2 和 3 请分别建立 issue 进行讨论
