### ISSUE TITLE
重庆电信职业学院

### ISSUE THREAD

**Issue by seien210300928** [mtf-wiki/RLE-wiki#51]
### 学校名称

重庆电信职业学院

### 地址位置

学校位于重庆市大足区双桥经开区巴岳大道9号

### 宿舍独立卫浴

全是独立卫浴

### 教学区第三卫生间

未发现

### 军训减免

可行

### 军训管不管头发

不要求短发，但长发要扎头发

### 体育减免

可行

### 医保的可用情况

否

### 校医院可用度

校医不能开HRT药物，没有医学院，无法校内检测激素

### 现状梗概

> **概况**

[重庆电信职业学院（Chongqing Electronic Information College，CEIC）](https://www.cqtc.edu.cn/)。全日制普通高等院校(民办专科)，七个院系三十四个专科专业，涵盖计算机相关、设计相关、幼教相关、体育相关、旅游相关、交通相关（具体的可以查看学校官网）。

> **地理位置及交通**

学校位于[重庆市大足区双桥经开区巴岳大道9号](https://surl.amap.com/2V6iQmWgdBs)，占地面积500余亩仅一个校区，但宿舍和教学楼在学校两边，中间夹着办公楼(学校称为“图书馆”)。
学校位于城郊，坐公交进城大概40分钟，没有地铁。大足火车站到学校北门打车费约30元，时间半个小时左右。

> **军训与体育**

对跨性别很友好，拿着易性症证明可以免军训（说治疗过程中易导致骨质疏松就行。在队伍边坐着玩，到时候记得带垫屁股的），不要求短发，但要扎头发，时间为期半个月，每天8:00-11:00、15:00-17:00、19:00-20:30。强度适中，军训与体育课不分男女，体育课可向老师说明情况，会有相应照顾，考核难度与教委要求一致，体测是否可以申请降低标准未知。

> **宿舍情况与基础设施**

对跨性别很友好，拿着易性症证明可以以一个人六人间价格 一个人住三人间（招生老师和辅导员会主动给你这样安排，如果是明年高中毕业的mtf可能就会和本文编辑者在一个寝室），mtf和ftm能否混住未知，已知mtf住男寝。有空调没风扇，六层无电梯。上床下桌。能信息盒和插板一个寝室会只有一样一个，暂时未发现电器功率限制（我还看见学校超市有卖1800w吹风机），独立卫浴。不用担心厕所问题，根据自己的实际情况(例如天赋度，自信度等)进厕所就行，但是要注意一下有的厕所没有隔门。未发现第三性别厕所。宿舍在北，教学楼在南
宿管阿姨人很善，只要自己不抵触，宿管最多只是想了解情况，其次还会格外关心跨跨的健康状态
热水1.5元/升，纯净水看宿舍走廊有没有纯净水饮水机，有就是1元/升，没有就只能找宿管买桶装水(得自己搬上楼)，13元/17.8升，桶装水押金30，水泵15。

> **医疗资源**

校医不能开HRT药物，需自行购买(有处方可以网购)，不能检查激素。最近医院为双桥经开区人民医院共体通桥分院，公交步行差不多都是40分钟；最近的三甲医院为重庆市大足区人民医院，公交1小时10分钟。都可检查，但不可开具处方与药物(具现有信息，重庆没有医院可以正常开处方)。

> **LGBT 友善梗概**

学校、教师、同学对 LGBT 友善，无lgbt相关组织，动漫社、文学社、舞蹈社、汉服社等泛ACGM社团对跨性别包容度很高。无LGBT科普活动，无专业心理医生，有心理老师，班级也有心理委员。校医很和蔼，基本是有求必应，校医平常也是很闲的。心理老师在授课期间会比较忙，不太好约，但一般辅导员和心理委员就能解决一部分的心理问。校内现未发现第二位跨性别。

> **院系探路**

学院间路程不大，集中在了教学楼一侧(学校南边)，但是宿舍到教学楼就得直穿整个学校了。

> **其他信息**

学校超市供应齐全，从电池到常用电器，饮料到桶装水到酸奶，水果都有，价格和一般实体店差不多（出了问题还能去理赔）。
食堂有面有菜，一食堂有冒菜、盖饭、汉堡，二食堂有称斤菜、面混沌、各种小吃、奶茶。价格正常，可加一元打包，非套餐的米饭一元随便加。
电信校园卡，速度还行，校内流量根本用不完，宽带100m满血（比某些家用100m快很多，稳定很多），套餐是20g全国+30g定向+240G校内+100分钟通话+100兆宽带。不能自己接路由器，有信息盒接网线，听说用路由器交换机等会限速甚至用不了，59元/月，第一个月50，合约1年或者2年
跨性别可算作医保外先天性疾病进行贫困申请，前提也是拿到证明
勤工俭学工资12元/小时，原则上每月工作不超过40小时，随时请假。其次还可能会有其它未列入勤工俭学计划的岗位，相关专业学生群会收到相应信息，这种工资就不确定了
社团包容性很强，至少在动漫社没有发现歧视跨性别的现象。其它学生在接触时也并未有心理同性很难接触的情况（可能也和外贸有一定关系）
学校北门围栏外有各种小吃、烧烤、炒饭、面条卖，商家会和学生隔栏交易。
学费以最贵的专业算：学费+住宿+书本=12000+1400+700=14100（元/年）
{{< sign-off-by "[晴渊](https://space.bilibili.com/291019982)" >}}

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by seien210300928** [comment]
错别字：倒数第三段，“外贸”本该为“外貌”

**Comment by seien210300928** [comment]
> ### 学校名称
> 重庆电信职业学院
> 
> ### 地址位置
> 学校位于重庆市大足区双桥经开区巴岳大道9号
> 
> ### 宿舍独立卫浴
> 全是独立卫浴
> 
> ### 教学区第三卫生间
> 未发现
> 
> ### 军训减免
> 可行
> 
> ### 军训管不管头发
> 不要求短发，但长发要扎头发
> 
> ### 体育减免
> 可行
> 
> ### 医保的可用情况
> 否
> 
> ### 校医院可用度
> 校医不能开HRT药物，没有医学院，无法校内检测激素
> 
> ### 现状梗概
> > **概况**
> 
> [重庆电信职业学院（Chongqing Electronic Information College，CEIC）](https://www.cqtc.edu.cn/)。全日制普通高等院校(民办专科)，七个院系三十四个专科专业，涵盖计算机相关、设计相关、幼教相关、体育相关、旅游相关、交通相关（具体的可以查看学校官网）。
> 
> > **地理位置及交通**
> 
> 学校位于[重庆市大足区双桥经开区巴岳大道9号](https://surl.amap.com/2V6iQmWgdBs)，占地面积500余亩仅一个校区，但宿舍和教学楼在学校两边，中间夹着办公楼(学校称为“图书馆”)。 学校位于城郊，坐公交进城大概40分钟，没有地铁。大足火车站到学校北门打车费约30元，时间半个小时左右。
> 
> > **军训与体育**
> 
> 对跨性别很友好，拿着易性症证明可以免军训（说治疗过程中易导致骨质疏松就行。在队伍边坐着玩，到时候记得带垫屁股的），不要求短发，但要扎头发，时间为期半个月，每天8:00-11:00、15:00-17:00、19:00-20:30。强度适中，军训与体育课不分男女
开局相关证明并体育课可向老师说明情况，会有相应照顾，考核难度与教委要求一致，体测可以按女生标准，但不排除比较老的老师会强行按男生标准。中奖党可100%按女生标准。跑步测试等强剧烈运动可直接及格。
> 
> > **宿舍情况与基础设施**
> 
> 对跨性别很友好，拿着易性症证明可以以一个人六人间价格 一个人住三人间（招生老师和辅导员会主动给你这样安排，如果是明年高中毕业的mtf可能就会和本文编辑者在一个寝室），mtf和ftm能否混住未知，已知mtf住男寝。有空调没风扇，六层无电梯。上床下桌。能信息盒和插板一个寝室会只有一样一个，暂时未发现电器功率限制（我还看见学校超市有卖1800w吹风机），独立卫浴。不用担心厕所问题，根据自己的实际情况(例如天赋度，自信度等)进厕所就行，但是要注意一下有的厕所没有隔门。未发现第三性别厕所。宿舍在北，教学楼在南 宿管阿姨人很善，只要自己不抵触，宿管最多只是想了解情况，其次还会格外关心跨跨的健康状态 热水1.5元/升，纯净水看宿舍走廊有没有纯净水饮水机，有就是1元/升，没有就只能找宿管买桶装水(得自己搬上楼)，13元/17.8升，桶装水押金30，水泵15。
> 
> > **医疗资源**
> 
> 校医不能开HRT药物，需自行购买(有处方可以网购)，不能检查激素。最近医院为双桥经开区人民医院共体通桥分院，公交步行差不多都是40分钟；最近的三甲医院为重庆市大足区人民医院，公交1小时10分钟。都可检查，但不可开具处方与药物(具现有信息，重庆没有医院可以正常开处方)。
> 
> > **LGBT 友善梗概**
> 
> 学校、教师、同学对 LGBT 友善，无lgbt相关组织，动漫社、文学社、舞蹈社、汉服社等泛ACGM社团对跨性别包容度很高。无LGBT科普活动，无专业心理医生，有心理老师，班级也有心理委员。校医很和蔼，基本是有求必应，校医平常也是很闲的。心理老师在授课期间会比较忙，不太好约，但一般辅导员和心理委员就能解决一部分的心理问。校内现未发现第二位跨性别。
> 
> > **院系探路**
> 
> 学院间路程不大，集中在了教学楼一侧(学校南边)，但是宿舍到教学楼就得直穿整个学校了。
> 
> > **其他信息**
> 
> 学校超市供应齐全，从电池到常用电器，饮料到桶装水到酸奶，水果都有，价格和一般实体店差不多（出了问题还能去理赔）。 食堂有面有菜，一食堂有冒菜、盖饭、汉堡，二食堂有称斤菜、面混沌、各种小吃、奶茶。价格正常，可加一元打包，非套餐的米饭一元随便加。 电信校园卡，速度还行，校内流量根本用不完，宽带100m满血（比某些家用100m快很多，稳定很多），套餐是20g全国+30g定向+240G校内+100分钟通话+100兆宽带。不能自己接路由器，有信息盒接网线，听说用路由器交换机等会限速甚至用不了，59元/月，第一个月50，合约1年或者2年 跨性别可算作医保外先天性疾病进行贫困申请，前提也是拿到证明 勤工俭学工资12元/小时，原则上每月工作不超过40小时，随时请假。其次还可能会有其它未列入勤工俭学计划的岗位，相关专业学生群会收到相应信息，这种工资就不确定了 社团包容性很强，至少在动漫社没有发现歧视跨性别的现象。其它学生在接触时也并未有心理同性很难接触的情况（可能也和外贸有一定关系） 学校北门围栏外有各种小吃、烧烤、炒饭、面条卖，商家会和学生隔栏交易。 学费以最贵的专业算：学费+住宿+书本=12000+1400+700=14100（元/年） {{< sign-off-by "[晴渊](https://space.bilibili.com/291019982)" >}}
> 
> ### 以 CC-BY-SA 4.0 协议分发
> * [x]  我同意以 CC-BY-SA 4.0 协议分发

**Comment by seien210300928** [comment]
> ### 学校名称
> 重庆电信职业学院
> 
> ### 地址位置
> 学校位于重庆市大足区双桥经开区巴岳大道9号
> 
> ### 宿舍独立卫浴
> 全是独立卫浴
> 
> ### 教学区第三卫生间
> 未发现
> 
> ### 军训减免
> 可行
> 
> ### 军训管不管头发
> 不要求短发，但长发要扎头发
> 
> ### 体育减免
> 可行
> 
> ### 医保的可用情况
> 否
> 
> ### 校医院可用度
> 校医不能开HRT药物，没有医学院，无法校内检测激素
> 
> ### 现状梗概
> > **概况**
> 
> [重庆电信职业学院（Chongqing Electronic Information College，CEIC）](https://www.cqtc.edu.cn/)。全日制普通高等院校(民办专科)，七个院系三十四个专科专业，涵盖计算机相关、设计相关、幼教相关、体育相关、旅游相关、交通相关（具体的可以查看学校官网）。
> 
> > **地理位置及交通**
> 
> 学校位于[重庆市大足区双桥经开区巴岳大道9号](https://surl.amap.com/2V6iQmWgdBs)，占地面积500余亩仅一个校区，但宿舍和教学楼在学校两边，中间夹着办公楼(学校称为“图书馆”)。 学校位于城郊，坐公交进城大概40分钟，没有地铁。大足火车站到学校北门打车费约30元，时间半个小时左右。
> 
> > **军训与体育**
> 
> 对跨性别很友好，拿着易性症证明可以免军训（说治疗过程中易导致骨质疏松就行。在队伍边坐着玩，到时候记得带垫屁股的），不要求短发，但要扎头发，时间为期半个月，每天8:00-11:00、15:00-17:00、19:00-20:30。强度适中，军训与体育课不分男女 开局相关证明并体育课可向老师说明情况，会有相应照顾，考核难度与教委要求一致，体测可以按女生标准，但不排除比较老的老师会强行按男生标准。中奖党可100%按女生标准。跑步测试等强剧烈运动可直接及格。
> 
> > **宿舍情况与基础设施**
> 
> 对跨性别很友好，拿着易性症证明可以以一个人六人间价格 一个人住三人间（招生老师和辅导员会主动给你这样安排，如果是明年高中毕业的mtf可能就会和本文编辑者在一个寝室），mtf和ftm能否混住未知，已知mtf住男寝。有空调没风扇，六层无电梯。上床下桌。能信息盒和插板一个寝室会只有一样一个，暂时未发现电器功率限制（我还看见学校超市有卖1800w吹风机），独立卫浴。不用担心厕所问题，根据自己的实际情况(例如天赋度，自信度等)进厕所就行，但是要注意一下有的厕所没有隔门。未发现第三性别厕所。宿舍在北，教学楼在南 宿管阿姨人很善，只要自己不抵触，宿管最多只是想了解情况，其次还会格外关心跨跨的健康状态 热水1.5元/升，纯净水看宿舍走廊有没有纯净水饮水机，有就是1元/升，没有就只能找宿管买桶装水(得自己搬上楼)，13元/17.8升，桶装水押金30，水泵15。
> 
> > **医疗资源**
> 
> 校医不能开HRT药物，需自行购买(有处方可以网购)，不能检查激素。最近医院为双桥经开区人民医院共体通桥分院，公交步行差不多都是40分钟；最近的三甲医院为重庆市大足区人民医院，公交1小时10分钟。都可检查，但不可开具处方与药物(具现有信息，重庆没有医院可以正常开处方)。
> 
> > **LGBT 友善梗概**
> 
> 学校、教师、同学对 LGBT 友善，无lgbt相关组织，动漫社、文学社、舞蹈社、汉服社等泛ACGM社团对跨性别包容度很高。无LGBT科普活动，无专业心理医生，有心理老师，班级也有心理委员。校医很和蔼，基本是有求必应，校医平常也是很闲的。心理老师在授课期间会比较忙，不太好约，但一般辅导员和心理委员就能解决一部分的心理问。校内现未发现第二位跨性别。
> 
> > **院系探路**
> 
> 学院间路程不大，集中在了教学楼一侧(学校南边)，但是宿舍到教学楼就得直穿整个学校了。
> 
> > **其他信息**
> 
> 学校超市供应齐全，从电池到常用电器，饮料到桶装水到酸奶，水果都有，价格和一般实体店差不多（出了问题还能去理赔）。 食堂有面有菜，一食堂有冒菜、盖饭、汉堡，二食堂有称斤菜、面混沌、各种小吃、奶茶。价格正常，可加一元打包，非套餐的米饭一元随便加。 电信校园卡，速度还行，校内流量根本用不完，宽带100m满血（比某些家用100m快很多，稳定很多），套餐是20g全国+30g定向+240G校内+100分钟通话+100兆宽带。不能自己接路由器，有信息盒接网线，听说用路由器交换机等会限速甚至用不了，59元/月，第一个月50，合约1年或者2年 跨性别可算作医保外先天性疾病进行贫困申请，前提也是拿到证明 勤工俭学工资12元/小时，原则上每月工作不超过40小时，随时请假。其次还可能会有其它未列入勤工俭学计划的岗位，相关专业学生群会收到相应信息，这种工资就不确定了 社团包容性很强，至少在动漫社没有发现歧视跨性别的现象。其它学生在接触时也并未有心理同性很难接触的情况（可能也和外貌有一定关系） 学校北门围栏外有各种小吃、烧烤、炒饭、面条卖，商家会和学生隔栏交易。 学费以最贵的专业算：学费+住宿+书本=12000+1400+700=14100（元/年） {{< sign-off-by "[晴渊](https://space.bilibili.com/291019982)" >}}
> 
> ### 以 CC-BY-SA 4.0 协议分发
> * [x]   我同意以 CC-BY-SA 4.0 协议分发

**Comment by seien210300928** [comment]
> ### 学校名称
> 重庆电信职业学院
> 
> ### 地址位置
> 学校位于重庆市大足区双桥经开区巴岳大道9号
> 
> ### 宿舍独立卫浴
> 全是独立卫浴
> 
> ### 教学区第三卫生间
> 图书馆楼某些地方有无障碍
> 
> ### 军训减免
> 可行
> 
> ### 军训管不管头发
> 不要求短发，但长发要扎头发
> 
> ### 体育减免
> 可行
> 
> ### 医保的可用情况
> 否
> 
> ### 校医院可用度
> 校医不能开HRT药物，没有医学院，无法校内检测激素
> 
> ### 现状梗概
> > **概况**
> 
> [重庆电信职业学院（Chongqing Electronic Information College，CEIC）](https://www.cqtc.edu.cn/)。全日制普通高等院校(民办专科)，七个院系三十四个专科专业，涵盖计算机相关、设计相关、幼教相关、体育相关、旅游相关、交通相关（具体的可以查看学校官网）。
> 
> > **地理位置及交通**
> 
> 学校位于[重庆市大足区双桥经开区巴岳大道9号](https://surl.amap.com/2V6iQmWgdBs)，占地面积500余亩仅一个校区，但宿舍和教学楼在学校两边，中间夹着办公楼(学校称为“图书馆”)。 学校位于城郊，坐公交进城大概40分钟，没有地铁。大足火车站到学校北门打车费约30元，时间半个小时左右。
> 
> > **军训与体育**
> 
> 对跨性别很友好，拿着易性症证明可以免军训（说治疗过程中易导致骨质疏松就行。在队伍边坐着玩，到时候记得带垫屁股的），不要求短发，但要扎头发，时间为期半个月，每天8:00-11:00、15:00-17:00、19:00-20:30。强度适中，军训与体育课不分男女 开局相关证明并体育课可向老师说明情况，会有相应照顾，考核难度与教委要求一致，体测可以按女生标准，但不排除比较老的老师会强行按男生标准。中奖党可100%按女生标准。跑步测试等强剧烈运动可直接及格。
> 
> > **宿舍情况与基础设施**
> 
> 对跨性别很友好，拿着易性症证明可以以一个人六人间价格 一个人住三人间（招生老师和辅导员会主动给你这样安排，如果是明年高中毕业的mtf可能就会和本文编辑者在一个寝室），mtf和ftm能否混住未知，已知mtf住男寝。有空调没风扇，六层无电梯。上床下桌。能信息盒和插板一个寝室会只有一样一个，暂时未发现电器功率限制（我还看见学校超市有卖1800w吹风机），独立卫浴。不用担心厕所问题，根据自己的实际情况(例如天赋度，自信度等)进厕所就行，但是要注意一下有的厕所没有隔门。未发现第三性别厕所。宿舍在北，教学楼在南 宿管阿姨人很善，只要自己不抵触，宿管最多只是想了解情况，其次还会格外关心跨跨的健康状态 热水1.5元/升，纯净水看宿舍走廊有没有纯净水饮水机，有就是1元/升，没有就只能找宿管买桶装水(得自己搬上楼)，13元/17.8升，桶装水押金30，水泵15。
> 
> > **医疗资源**
> 
> 校医不能开HRT药物，需自行购买(有处方可以网购)，不能检查激素。最近医院为双桥经开区人民医院共体通桥分院，公交步行差不多都是40分钟；最近的三甲医院为重庆市大足区人民医院，公交1小时10分钟。都可检查，但不可开具处方与药物(具现有信息，重庆没有医院可以正常开处方)。
> 
> > **LGBT 友善梗概**
> 
> 学校、教师、同学对 LGBT 友善，无lgbt相关组织，动漫社、文学社、舞蹈社、汉服社等泛ACGM社团对跨性别包容度很高。无LGBT科普活动，无专业心理医生，有心理老师，班级也有心理委员。校医很和蔼，基本是有求必应，校医平常也是很闲的。心理老师在授课期间会比较忙，不太好约，但一般辅导员和心理委员就能解决一部分的心理问。校内现未发现第二位跨性别。
> 
> > **院系探路**
> 
> 学院间路程不大，集中在了教学楼一侧(学校南边)，但是宿舍到教学楼就得直穿整个学校了。
> 
> > **其他信息**
> 
> 学校超市供应齐全，从电池到常用电器，饮料到桶装水到酸奶，水果都有，价格和一般实体店差不多（出了问题还能去理赔）。 食堂有面有菜，一食堂有冒菜、盖饭、汉堡，二食堂有称斤菜、面混沌、各种小吃、奶茶。价格正常，可加一元打包，非套餐的米饭一元随便加。 电信校园卡，速度还行，校内流量根本用不完，宽带100m满血（比某些家用100m快很多，稳定很多），套餐是20g全国+30g定向+240G校内+100分钟通话+100兆宽带。不能自己接路由器，有信息盒接网线，听说用路由器交换机等会限速甚至用不了，59元/月，第一个月50，合约1年或者2年 跨性别可算作医保外先天性疾病进行贫困申请，前提也是拿到证明 勤工俭学工资12元/小时，原则上每月工作不超过40小时，随时请假。其次还可能会有其它未列入勤工俭学计划的岗位，相关专业学生群会收到相应信息，这种工资就不确定了 社团包容性很强，至少在动漫社没有发现歧视跨性别的现象。其它学生在接触时也并未有心理同性很难接触的情况（可能也和外貌有一定关系） 学校北门围栏外有各种小吃、烧烤、炒饭、面条卖，商家会和学生隔栏交易。 学费以最贵的专业算：学费+住宿+书本=12000+1400+700=14100（元/年） {{< sign-off-by "[晴渊](https://space.bilibili.com/291019982)" >}}
> 
> ### 以 CC-BY-SA 4.0 协议分发
> * [x]    我同意以 CC-BY-SA 4.0 协议分发

**Comment by ArtsEpiphany** [comment]
感谢投稿！
