### ISSUE TITLE
华侨大学（厦门校区）

### ISSUE THREAD

**Issue by timi137137** [mtf-wiki/RLE-wiki#52]
### 学校名称

华侨大学

### 地址位置

福建省厦门市集美区集美大道668号（厦门校区）

### 宿舍独立卫浴

六人间四人间有单独厕所单独淋浴，干湿分离。二人间单独厕所淋浴，干湿不分

### 教学区第三卫生间

无

### 军训减免

未知

### 军训管不管头发

据我所知根据部队规范走

### 体育减免

待补充，还没询问

### 医保的可用情况

可用

### 校医院可用度

未知，待询问

### 现状梗概

该学校对MTF较为友好，且校内有不少同类。

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by ArtsEpiphany** [comment]
感谢投稿！如果希望署名，请提供你希望使用的名称，我们会添加到对应的页面～
