### ISSUE TITLE
重庆大学校医院性激素六项信息

### ISSUE THREAD

**Issue by nekoakaido** [mtf-wiki/RLE-wiki#54]
### RLE.wiki URL

https://rle.wiki/campus/CQU.html

### 内容

虎溪校区校医院每周三上午可做性激素六项检查

**Comment by ArtsEpiphany** [comment]
感谢投稿！ 已在<https://github.com/mtf-wiki/RLE-wiki/commit/0b303e6cdf08f4764da89aa6d0af0f832c29e399>中更新。
