### ISSUE TITLE
请求新增学校：哈尔滨工业大学（深圳）

### ISSUE THREAD

**Issue by takehana-chan** [mtf-wiki/RLE-wiki#56]
### 学校名称

哈尔滨工业大学（深圳）

### 地址位置

深圳市南山区桃源街道深圳大学城哈尔滨工业大学校区

### 宿舍独立卫浴

校内宿舍有独立卫浴。四间寝室共享四个浴室，或者两间寝室共享两个浴室，一间寝室有四个人。浴室用毛玻璃隔板隔开，门也是毛玻璃门。本科生住在校内新宿舍，研究生有可能会住在校外的公寓（宿舍），校外公寓的情况尚不明确。若研究生的法定有效证件上的性别为女性，有可能住在校内。

### 教学区第三卫生间

所有建筑物均有无障碍卫生间，但是大多数教学楼（如 H、T2、T3、T4、T5、T6）的无障碍卫生隔间均设置在男、女厕所内。信息楼（L）的无障碍卫生间设置在男、女厕所之外，研究生院的部分卫生间也是如此。总体而言，对于本科生经常去的教学楼都是将无障碍卫生隔间设置在男、女厕所之内。

### 军训减免

不了解

### 军训管不管头发

不了解

### 体育减免

不了解

### 医保的可用情况

深圳大学生医保，需要经过社康转诊后方可使用。一般而言，是到学校隔壁的平山村社康转诊到南方科技大学医院进行就诊，可报销绝大多数费用。

以下附加内容（适用于 2022~2023 年度）摘自校内信息网站，该网站不允许校外人员访问：

> 缴费标准：本年度大学生医保费用为1244.52元，其中深圳市政府补助666元，个人只需缴费578.52元。
>
> 参保待遇：大学生医保包括大病门诊、住院医疗保险和社康门诊待遇，具体按照《深圳市社会医疗保险办法》中二档医疗保险的规定执行。
>
> 保障时间：大学生医保参保时间为每年9月，一次性缴纳当年9月至次年8月的医疗保险费，从当年10月至次年9月，按规定享受医疗保险待遇。对于首次参保的大学生，如当年9月发生住院医疗费用的，也可按规定享受医疗保险待遇，参保学生可告知医院已办理参保登记，先交足押金，待参保缴费到账并到规定的银行网点制作金融社保卡后，到医院补记账。
>
> 2022年度新参加大学生医保学生**均需办理金融社保卡**（已持有深圳市金融医保卡的学生不需要办理），才能正常使用医保卡。
>
> 参保大学生的普通门诊应在绑定的定点医疗机构就医。学生可登录社保局网站中“个人服务网上系统”选定一家社康中心作为定点医疗机构（具体操作流程请参考附件4，**推荐绑定平山社康**）；或关注“深圳社保”微信公众号，选择“便民服务”进行办理；也可直接到就近社康中心办理绑定。绑定医疗机构后1个月内不得变动。

### 校医院可用度

无校医院，清华园区有社康（不过开放时间比平山村社康短，而且也远一点点）。激素检查为通过社康转诊到南方科技大学医院进行，尚不明确能不能开到激素药。

### 现状梗概

关于学校的其他信息在学校官网（[www.hitsz.edu.cn](https://www.hitsz.edu.cn)）、招生宣传手册或者招生办的官方社交媒体账号均可获取到，且比较全面详尽，便不在此赘述。

笔者所接触的师生总体上不会歧视 MtF 群体，有的同学比较友跨（但尚不明确具体的比例，有待进一步观察），也有的同学发表过针对 LGBT 的仇恨言论。学校中指派性别（sex assigned at birth）的比例总体而言男性比女性多很多，除了经管类专业女性占多之外，其他专业都是男性占多，具体可参见学校官方公布的信息。学校在疫情期间（准确的说已经常态化了）出入校采用报备制，不同学院不同年级的严格程度都不一样，可能对就医带来一定程度的困难。距离学校比较近的医院还有深圳大学总医院，笔者感觉比南方科技大学医院要好，但是无法使用深圳大学生医保（即深圳少儿医保）。学校的 MtF / MtX 群体规模尚不明确，但是至少有 4 人。其他信息有待补充。

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by septs** [comment]
CC @billchenchina

**Comment by billchenchina** [comment]
> CC @billchenchina

我是本部的，不了解深圳啊（

**Comment by LittleYe233** [comment]
涉及本科生及就医情况的相关信息基本属实。对研究生的相关信息不了解。

**Comment by takehana-chan** [comment]
已根据征集到的意见修改和新增一些内容。

**Comment by rewired-gh** [comment]
情况属实
![LGTM](https://n.hopp.top/lgtm.svg)

**Comment by ArtsEpiphany** [comment]
感谢投稿！如果希望署名，请提供你希望使用的名称，我们会添加到对应的页面～

**Comment by takehana-chan** [comment]
> 感谢投稿！如果希望署名，请提供你希望使用的名称，我们会添加到对应的页面～

希望使用的名称：Takehana
谢谢
