### ISSUE TITLE
优秀案例征集询问和一些建议

### ISSUE THREAD

**Issue by Mister-Hope** [mtf-wiki/RLE-wiki#58]
hello，这里是 vuepress2 核心团队成员以及 vuepress theme hope 的开发者 Mr.Hope。

> 通过 Issue 联系是因为贵仓库并未开启（或有意关闭了 Dicussion 面板），不清楚是有意为之还是没有开放。

向贵方联系主要是今天想整理一些优秀案例到主题的 [官网文档](https://vuepress-theme-hope.github.io/v2/zh/demo.html) 上，鉴于贵方项目有一定特殊性，故来征集一下项目本身维护者的意见，关于将此项目录入项目案例中的行为。

---

此外，在简单观察此项目后，我会稍后以 PR 形式，直接新增东北师范大学的简介。

另外，鉴于鄙人在自己母校迎新 5 届新生，个人独立开发维护了 75 万字的 in 东师小程序(见下)，冒昧提出几点建议：

1. 由于中国国情导致网站显著弱于社交媒体（微博、微信公众号、小程序、抖音等），可以考虑在 markdown 之外创建通用数据，进行更多形式发布（如微信小程序）
2. 创建的模板非常有待细化，一个相当有帮助的建议是应该在模板顶部增加 https://rle.wiki/contributor-guide/campus.html 的链接，以更好地提升指南质量。

最后，为项目的发起和维护者表示鼓励，尽管我不属于相关群体，但是我充分理解少数群体所含有的特殊需求，可能会在解决中遇到很大困难。我本人也在校园生活中一直致力于做类似的事情，为未步入社会的学生提供帮助。祝项目顺利，一切都好。

**Comment by septs** [comment]
对于问题 1，鉴于目前国内平台对 LGBT+ 内容具有强烈的排斥性
see https://www.bbc.com/zhongwen/simp/chinese-news-57763594

对于问题 2，从行文撰稿的角度来说提供 结构化模版 确实有助于保持 内容阅读风格的一致性

**Comment by Mister-Hope** [comment]
我的意思是改进这一部分，我觉得在描述里增加 https://rle.wiki/contributor-guide/campus.html 的链接是最起码有帮助的。
![image](https://user-images.githubusercontent.com/33315834/195572297-ac9c2c67-9056-4141-be77-7b172fd88edd.png)

**Comment by Mister-Hope** [comment]
此外，我觉得全站搜索是有必要的，不清楚贵方是否尝试申请 docsearch 以及是否在申请途中遇到了问题。

**Comment by septs** [comment]
目前本项目未处于积极维护状态，您提到的事项我们将在后续维护中考虑。

以目前的信息量尚不需要站内搜索介入

**Comment by Mister-Hope** [comment]
上述只是提出几点建议。考虑到贵方项目的复杂性以及政府立场的不定性，我就不考虑收录项目了。此 Issue 的主题已经几乎全部处理完毕。如需要我帮助维护站点（VuePress，主题以及网站样式本身，不包含内容）欢迎提出。
