### ISSUE TITLE
东北师范大学

### ISSUE THREAD

**Issue by Mister-Hope** [mtf-wiki/RLE-wiki#59]
### 学校名称

东北师范大学

### 地址位置

吉林长春

### 宿舍独立卫浴

无

### 教学区第三卫生间

无

### 军训减免

凭材料，详见 https://github.com/Hope-Studio/innenu-res/blob/main/res/guide/activity/military/exempt.yml

### 军训管不管头发

否

### 体育减免

凭材料，详见 https://github.com/Hope-Studio/innenu-res/blob/main/res/guide/test/pe-test/exempt.yml

### 医保的可用情况

详见 https://github.com/Hope-Studio/innenu-res/blob/main/res/guide/insurance/index.yml

### 校医院可用度

上述均否，介绍详见 https://github.com/Hope-Studio/innenu-res/blob/main/res/intro/apt/hospital/index.yml

### 现状梗概

更多介绍详见 in 东师小程序。

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by Mister-Hope** [comment]
上述提及链接所包含文件以及文件内所涉及的其他文件内容，本人含有版权的，**同意以 CC-BY-SA 4.0 协议分发**

注: 以上内容包含极少量非本人版权内容，如校医院介绍来自学校相关部门材料或官网，我无法转让版权，也无法承诺以 CC-BY-SA 4.0 分发。其他如体测、军训免测材料为学校文件，同样非本人版权内容，也无法承诺以 CC-BY-SA 4.0 分发。

**Comment by septs** [comment]
考虑到，本站面向受众为 MtF / FtM 您所提供的内容中并无她/他所关心的内容

因此本 issue 将 close，如有后续 MtF / FtM 提交贵校内容，我邀请您参与检查

顺颂文祺

**Comment by Mister-Hope** [comment]
我只是简单的 link 了一下，除了我提及的文件之外，你们可以自由从 in 东师摘录你们需要的内容并交予我审查，相关内容我都可以放弃 CC BY-NC-ND 4.0，允许你们 CC-BY-SA 4.0。就以第一所学校 https://rle.wiki/campus/SUMHS.html 为例作比较，除小程序未明确提及校医院是否可以开激素药外，其他同类内容只多不少。

说句不客气的，如果说你觉得 75 万字的东西，不包含  MtF / FtM 关心的内容，那大概是你有什么认知问题。

**Comment by Mister-Hope** [comment]
另外参考其他内容做几点补充：

1. 厕所隔间有锁
2. 本部校区图书馆包含无障碍卫生间


补充 LGBT 概述

1. 学校内男女比例 3:7，校园内可见部分异性衣装穿着的男/女性。
2. 存在男生有留长发的情况，学校内无外观或衣装检查与规范，学校学院辅导员都不管
3. 在校 6 年听说有 MtF，本校大部分同学都不会产生歧视，了解到有女装男性，不清楚是否是 FtM 还是单纯异装癖不做评价。
4. 社团基本不会歧视相关群体，但学院团学组织要看辅导员以及团委书记态度，一般情况下还好。
5. 由于师范院校本身贫困生比例也很大，考虑到我视角里的近百名教职工对吃不起饭、穿不起衣服、英语差到爆、心理问题导致交流障碍、普通话问题导致交流障碍等若干情况均有包容，大部分教职工（任课教师以及相关机构工作人员与领导）应该不会歧视。

学校执行规章制度较为严格，故个人不认为体育、军训可以在相关文件规定之外的情形下进行《商讨》。
