### ISSUE TITLE
天津外国语大学

### ISSUE THREAD

**Issue by yuiko8848** [mtf-wiki/RLE-wiki#60]
### 学校名称

天津外国语大学

### 地址位置

天外有两个校区：马场道校区和滨海校区。马场道校区位于天津市河西区117号；滨海校区位于大港学府路60号（离市区较远，可乘地铁或者公交）。马场道校区面积仅为滨海校区面积的九分之一。

### 宿舍独立卫浴

两校区均无独立卫浴，更衣大厅没有任何阻挡物，对xyn极不友好，时常有校外人员进入。看门大爷也会巡视。澡堂部分位置有挡板，半包围结构，无挡板位置两人间隔15cm左右，如需独立卫浴可向学校申请走读或者住进国际交流中心。

### 教学区第三卫生间

马场道校区继续教育学院有，两校区主教学楼逸夫楼没有，每层楼男厕一个和女厕三个。

### 军训减免

凭三甲医院病例或诊断证明可加入见习队伍。仅帮老师做事但需要参加考试。实测假条和hrt处方无效。平时军训比较轻松（可摸鱼）。

### 军训管不管头发

无，着装整洁即可。

### 体育减免

不可协商减免。除重大疾病可凭三甲医院证明减免外（按60分计算成绩）必须参加。考试对xyn及格难度较高（本人挂过两次）。

### 医保的可用情况

暂未使用过，不太了解。

### 校医院可用度

完全无法使用。不能进行激素检查，连最基本的一些药都时常没有，不能开激素药物和精神类药物。并且只要去过医务室就会登记上报。个人信息泄漏严重，医生水平堪忧，建议校外就医。

### 现状梗概

        本校男女比例0.28:1，位于全国前列。
        外卖方面，学校新建了外卖柜，可以无接触配送（部分柜门打不开，小心被坑），因此购买hrt药物较为隐私。
快递方面，取快递时只会核对手机号，而且可以自助扫码取件，不会被人查看核对快递物品。（有概率丢件）
        学校目前已知xyn只有咱一人。对RLE友好，本人目前没有遇到什么大的阻力。
学校大环境对LGBT群体友好，大多数人不会刻意排斥。教师大多数对MtF态度友好，不会产生偏见。学校对着装没有什么要求，得体即可。辅导员态度中立，在不发生严重后果的情况下不会干预，个别学院辅导员会联系家长。男寝gay和GD数量多。学校管理层保守派居多，形式主义较重。
        生活方面，寝室是八人间，上下铺，部分寝室没有桌子（咱的），宿舍楼每层厕所有全封闭隔间，衣物晾晒只能使用公共区域，隐私性差，时常丢衣服。洗衣室内洗衣机相互独立，一般看不到放了什么衣服，机门他人无法打开。室友看运气，两极差距大，有的寝室包容度高且十分和谐，但有的寝室八个人十个群（还是咱的）。
        不要去学校心理咨询室，今天说的内容可能明天全学院都知道了，而且会向学院上报，咨询师大多没有良好的专业能力，会有反作用。
        社团方面，院学生会形式主义，校学生会较好。社团活动友好，没有偏见。
        医疗方面，若需要查六项，可在周围三甲医院挂内科或内分泌科就诊（限马场道校区），据说安定医院可开证，三中心医院医生友跨，其他医院可自费开检查。公共交通方便。
        不要参加学校任何心理测试，尤其是那些送小物品的（本人有幸被钓过鱼，喜提辅导员面谈）。
邮箱：KurugayaYuiko@163.com
{{<sign-off-by “唯”>}}
        

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by yuiko8848** [comment]
修改邮箱为KurugayaYuiko@126.com

**Comment by ArtsEpiphany** [comment]
> 男寝gay和GD数量多

你或许想说的是CD（异装）？

**Comment by ArtsEpiphany** [comment]
感谢投稿！

**Comment by yuiko8848** [comment]
> 

对的，此处打错了
