### ISSUE TITLE
北京工商大学

### ISSUE THREAD

**Issue by Unknown-Error-0311** [mtf-wiki/RLE-wiki#70]
### 学校名称

北京工商大学

### 地址位置

北京市房山区良乡高教园区

### 宿舍独立卫浴

仅良乡校区新宿舍有独立卫浴，据说公共澡堂没有隔板

### 教学区第三卫生间

没有

### 军训减免

可凭医学材料减免

### 军训管不管头发

19级以后均在校内军训，军训手册虽然要求男生不留长发，但是不会强制要求理发，可以正常通过军训，军训期间见过很多留长发的男生。

### 体育减免

可凭医学材料减免，学校体测通知说现阶段体测成绩不影响毕业

### 医保的可用情况

公费医疗，需要先到校医院就诊再转诊

### 校医院可用度

不了解

### 现状梗概

- 学校的氛围还是比较开放包容的，穿衣打扮都很自由，在学校可以日常女装，目前的老师和辅导员还是比较友好的，没有发生过歧视。
- 军训时有被要求回去理发，但是拒绝理发也没人会管，最后我的军训成绩比平均水平低点，反正能过就行了。据我观察，有好多个长发的男生都一直没有理发，所以军训的问题不会很大。也可以加入新闻中心写写稿子或者去拍照，这样可以光明正大的不去军训。实在是担心了话，可以免训，想办法办个病假条就行。
- 学校目前体测不影响毕业，如果不参与评奖评优，那大三大四的体测完全无所谓了，但是大一大二的体测占体育课成绩，并且体育课还要跑2000米，这个就比较麻烦了。
- 学校允许办理走读，可以自己在外面租房子。本科生应该是19级部分学生住的新宿舍，条件确实好，4人间上床下桌，有独立卫浴24小时热水，浴室的吹头机电源24小时有电不限功率，可以拉插线板出来接电脑，别被宿管发现就行。住宿费一年好像是960。

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by Cryolitia** [comment]
是否需要匿名

**Comment by Rinfair-CSP-A016** [comment]
@VincentSHI1230 来补充点什么吗？

**Comment by VincentSHI1230** [comment]
OK，我来发Pr

**Comment by VincentSHI1230** [comment]
咦？`BTBU.md` 的上一个Pr竟然还没有收录

**Comment by Cryolitia** [comment]
@VincentSHI1230 可以直接在那个pr基础上改（？

**Comment by VincentSHI1230** [comment]
我先等收录吧（趴
@管理

**Comment by ArtsEpiphany** [comment]
@VincentSHI1230 这个Issue已经被收录了，辛苦你来再补充一些内容吧qwq

**Comment by VincentSHI1230** [comment]
@ArtsEpiphany 已补充，晚安。

**Comment by Rinfair-CSP-A016** [comment]
Closed due to commit b30d75e
