### ISSUE TITLE
浙江农林大学ZAFU

### ISSUE THREAD

**Issue by tuboshufps** [mtf-wiki/RLE-wiki#76]
### 学校名称

浙江农林大学

### 地址位置

浙江省杭州市临安区武肃街666号/衣锦街252号

### 宿舍独立卫浴

有

### 教学区第三卫生间

无

### 军训减免

有

### 军训管不管头发

不管

### 体育减免

有，可以凭易性症/性身份障碍病历申请保健班免除体测，但体育分仅有60分。

### 医保的可用情况

有，杭州市大学生医保，可以去临安区中医院/临安区人民医院测六项/买补佳乐

### 校医院可用度

可用度几乎为0

### 现状梗概

概況：浙江农林大学（Zhejiang Agriculture and Forestry University）是一所位于杭州市临安区的综合大学，又称临安农专、皇家农林，有衣锦、东湖两个校区。其中衣锦校区位于衣锦街252号，区政府隔壁，因为较高的女生比例和较小的规模，又称衣锦女高；东湖校区位于武肃街666号，大部分的学生在这个校区。
医疗资源：医务室没有补子
如果办理了大学生医保，可以去临安中医院（二甲，正在申三乙，报销比例60%），可以开六项（180元，医保后77元）或者单开除了睾酮以外的五项（没有睾酮！）
（约12一盒，一次限两盒，挂内分泌科，比较友好）
或者去临安人民医院（三乙，报销比例40%），可以挂内科、全科、内分泌科（建议皮肤科，没人），进去直接说开检查，可以单开除了孕酮以外的五项（没有孕酮！）
另外，可以去卫生院开补子，一次限制两盒 ，两次之间需间隔9天以上
以上开补子需要有三甲医院的处方
距离临安最近的三甲是浙一余杭院区，精神科碰运气能开到大证，内分泌科不如浙二友跨，也得碰运气 
军训与体育
军训比较好请假，但不知道可不可以凭证请（本人是在军训刚开始站了十分钟就晕倒，然后在什么医疗证明都没有的情况下被建议请假了）
体育课不分男女，但因为本校女生较多，对体力较弱的也很照顾。
如果无力体测，可以凭易性症/性身份障碍病历申请保健班免除体测，但体育分仅有60分。（我去盖章的时候，体育军训部的副主任说第一次见） 
宿舍：有四人寝和六人寝，随机分配？可以和同学协调换寝室，但因为床位比较紧张，没有单人寝。
可以租房，但是有问题学生清单，去申请可能会有更多要求
租金单人的单间从600一个月到2000
（合租招租中，有意请联系cm_1670@outlook.com）
LGBT友善度：有Gay和Les的圈子，但是没有公开的社团，所以没了解过，没有见到过其他Trans
男性中有不少恐同的
但对于Trans的了解近乎玩梗，如果在q群里宣传相关内容会被警告
有心理咨询，但是不敢去
对RLE还是相对宽容的，男寝穿jk根本没人看，去上课也不会被注目
文法学院的两位辅导员都比较友跨。其中有一位在上大学（本校）时有一位同学在毕业之后变性，因此也对跨性别有些认识。

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by Cryolitia** [comment]
请问是否需要署名，如需要署名应如何称呼您

**Comment by tuboshufps** [comment]
> 请问是否需要署名，如需要署名应如何称呼您

不需要，谢谢
