### ISSUE TITLE
山东大学（济南校本部及青岛校区，招生代码10422）

### ISSUE THREAD

**Issue by Kazhaha** [mtf-wiki/RLE-wiki#90]
### 学校名称

山东大学

### 地址位置

中心校区（济南市历城区山大南路27号）洪家楼校区（济南市历城区洪家楼5号） 趵突泉校区（济南市历下区文化西路44号） 千佛山校区（仅研究生，济南市历下区经十路17923号） 兴隆山校区（济南市市中区二环东路12550号）  软件园校区（济南市历城区舜华路中段1500号） 青岛校区（青岛市即墨区滨海公路72号）

### 宿舍独立卫浴

青岛校区有独立卫浴，中心校区部分宿舍楼有独立卫浴，兴隆山校区部分宿舍楼有独立卫生间，其他无。公共浴室私密度良好

### 教学区第三卫生间

没有，仅有男、女两性卫生间

### 军训管不管头发

露出的部分不超过肩膀，颜色不夸张即可

### 医保的可用情况

济南校本部参考济南市学生医保覆盖范围，需校医院转诊，青岛不清楚

### 校医院可用度

兴隆山校区校医院不能，其他校区不清楚，激素检查可前往趵突泉校区对面的齐鲁医院

### 现状梗概

学校心理健康中心每周可提供一次免费线上或线下一对一心理咨询服务，时间为50分钟，各个校区均有线下心理咨询室，提前至少24小时预约即可。大部分咨询师跨性别友好，但是对跨性别的了解十分有限，以至于有些时候都变成就听你在说。
辅导员和同学大多友跨，部分学院领导可能会不太理解（认为应该等到能承受这些事的后果是时候才开始hrt等等）
本科生院官网上有“学信网全日制本专科学历信息勘误办理指南”，链接：[](url)](https://www.bkjx.sdu.edu.cn/info/1309/33072.htm)。但缺乏跨性别者修改成功的案例报告。
学校内mtf深柜居多，能了解到的极少。
校内住宿四人间一年1200，六人间一年800，每学年第一学期和注册费还有第一学期的学分费一起缴纳。全校校园网覆盖，宿舍提供免费无线和有线网络（学校内网千兆，外网网速各校区限速不同），不可自行拉宽带。每个宿舍每个月提供实际居住人数*4度免费用电，超出部分按照济南市居民用电收费标准缴纳（夏天和冬天的空调开销较高）。
大部分学院在学生强烈要求以及父母知情同意的情况下允许独自或和同学一起校外住宿，中心校区、洪家楼校区和趵突泉校区校外住宿的同学较多，兴隆山校区和软件园校区的较少。兴隆山校区附近租房不太方便，两室一厅或两厅的话，离学校很近的南山小区和教师公寓2300-2800不等，比较老旧的兴隆山庄和学府西苑1400左右，较远但比较新的搬倒井鑫苑1700左右（该小区有一室一厅，1400左右），距离合适且周围设施完善的华润中央公园2500-3200（该小区物业较贵，2.365r/月/m2）。冬季供暖方面，使用天然气壁挂炉的一方燃气3.3r，集中供暖每个供暖季每平方26.8r/m2（实际上会有出入，笔者住89m2的出租屋，一个供暖季1700多点）。

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by Cryolitia** [comment]
@Kazhaha 是否需要署名

**Comment by Kazhaha** [comment]
> @Kazhaha 是否需要署名

署名： Annie Chorly 邮箱：kazhaha@qq.com
